import {Inter, Roboto, Russo_One} from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header";

const inter = Inter({subsets: ["latin"]});
// const russo = Russo_One({subsets: ["latin"], weight: "400"})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Header/>
        {children}

        <script src="https://kit.fontawesome.com/807ba58bd3.js" crossOrigin="anonymous"></script>
        </body>
        </html>
    );
}
